services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: testando123
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: testando123